export default {
  logo: require("./logo.png"),
  denied: require("./accessdenied.png"),
  placeHolder: require("./generic.png"),
  goal: require("./goal.jpg"),
  account: require("./account.jpg"),
  welcome: require("./welcome.jpg"),
  sport1: require("./sportHome1.jpg"),
  sport2: require("./sportHome2.jpg"),
  home1: require("./home1.jpg"),
  subscription: require("./subscription.jpg"),
  house: require("./house.jpg"),
  gym: require("./gym.jpg"),
  homme: require("./homme.png"),
  femme: require("./femme.png"),
  workout: require("./workout.jpg"),
  genderBg: require("./genderBackground.jpg"),
  age: require("./age.jpg"),
  blue:require("./blue.jpg"),
  workoutDays:require("./workoutDaysBg.jpg"),
  allergies:require("./allergies.jpg"),
  nutrition:require("./nutrition.jpg"),
  retry:require("./reload.png"),
  arm:require("./arm.jpeg"),
  home:require("./home.jpg"),
  height:require("./height.jpeg"),
  Gluteband: require("./Gluteband.jpg"),
  Haleres: require("./Haleres.jpg"),
  Kettlebell: require('./Kettlebell.jpeg'),
  Lestes: require('./Lestes.jpg'),
  sansMateriel: require('./sansMatiriel.jpg'),
  elastique: require('./elastique.jpeg'),
  swissball: require('./swissball.jpeg'),
};
